plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.2'
}

group = 'su.deworld'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
    compileOnly 'org.slf4j:slf4j-api:2.0.9'

    // Discord
    implementation('net.dv8tion:JDA:5.3.0') {
        exclude module: 'opus-java'
    }

    // Telegram
    implementation 'org.telegram:telegrambots-longpolling:7.10.0'
    implementation 'org.telegram:telegrambots-client:7.10.0'
}

shadowJar {
    archiveClassifier.set('')
    archiveFileName.set("DwChat.jar")

    relocate 'net.dv8tion',      'su.deworld.dwchat.libs.jda'
    relocate 'org.telegram',     'su.deworld.dwchat.libs.telegram'
    relocate 'com.fasterxml',    'su.deworld.dwchat.libs.jackson'
    relocate 'okhttp3',          'su.deworld.dwchat.libs.okhttp'
    relocate 'okio',             'su.deworld.dwchat.libs.okio'
    relocate 'gnu.trove',        'su.deworld.dwchat.libs.trove'
    relocate 'org.apache.commons','su.deworld.dwchat.libs.commons'

    minimize {
        exclude(dependency('net.dv8tion:JDA:.*'))
        exclude(dependency('org.telegram:.*'))
    }
}

tasks.named('build') { dependsOn shadowJar }
compileJava.options.encoding = 'UTF-8'